config/routes.rb
Rails.application.routes.draw do
  resources :localizacao_onibuses
  resources :onibuses
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/localizacao_onibus.rb
class LocalizacaoOnibus < ApplicationRecord
end

app/models/onibus.rb
class Onibus < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/localizacao_onibuses_controller.rb
class LocalizacaoOnibusesController < ApplicationController
  skip_before_action :authenticate_user!
  before_action :set_localizacao_onibus, only: [:show, :edit, :update, :destroy]

  # GET /localizacao_onibuses
  # GET /localizacao_onibuses.json
  def index
    @localizacao_onibuses = LocalizacaoOnibus.all
  end

  # GET /localizacao_onibuses/1
  # GET /localizacao_onibuses/1.json
  def show
  end

  # GET /localizacao_onibuses/new
  def new
    @localizacao_onibus = LocalizacaoOnibus.new
  end

  # GET /localizacao_onibuses/1/edit
  def edit
  end

  # POST /localizacao_onibuses
  # POST /localizacao_onibuses.json
  def create
    @localizacao_onibus = LocalizacaoOnibus.new(localizacao_onibus_params)

    respond_to do |format|
      if @localizacao_onibus.save
        format.html { redirect_to @localizacao_onibus, notice: 'Localizacao onibus was successfully created.' }
        format.json { render :show, status: :created, location: @localizacao_onibus }
      else
        format.html { render :new }
        format.json { render json: @localizacao_onibus.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /localizacao_onibuses/1
  # PATCH/PUT /localizacao_onibuses/1.json
  def update
    respond_to do |format|
      if @localizacao_onibus.update(localizacao_onibus_params)
        format.html { redirect_to @localizacao_onibus, notice: 'Localizacao onibus was successfully updated.' }
        format.json { render :show, status: :ok, location: @localizacao_onibus }
      else
        format.html { render :edit }
        format.json { render json: @localizacao_onibus.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /localizacao_onibuses/1
  # DELETE /localizacao_onibuses/1.json
  def destroy
    @localizacao_onibus.destroy
    respond_to do |format|
      format.html { redirect_to localizacao_onibuses_url, notice: 'Localizacao onibus was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_localizacao_onibus
      @localizacao_onibus = LocalizacaoOnibus.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def localizacao_onibus_params
      params.require(:localizacao_onibus).permit(:Usuario_Id, :Onibus_Id_Onibus, :Localizacao, :Data_2, :Hora)
    end
end

app/controllers/onibuses_controller.rb
class OnibusesController < ApplicationController
  before_action :set_onibus, only: [:show, :edit, :update, :destroy]

  # GET /onibuses
  # GET /onibuses.json
  def index
    @onibuses = Onibus.all
  end

  # GET /onibuses/1
  # GET /onibuses/1.json
  def show
  end

  # GET /onibuses/new
  def new
    @onibus = Onibus.new
  end

  # GET /onibuses/1/edit
  def edit
  end

  # POST /onibuses
  # POST /onibuses.json
  def create
    @onibus = Onibus.new(onibus_params)

    respond_to do |format|
      if @onibus.save
        format.html { redirect_to @onibus, notice: 'Onibus was successfully created.' }
        format.json { render :show, status: :created, location: @onibus }
      else
        format.html { render :new }
        format.json { render json: @onibus.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /onibuses/1
  # PATCH/PUT /onibuses/1.json
  def update
    respond_to do |format|
      if @onibus.update(onibus_params)
        format.html { redirect_to @onibus, notice: 'Onibus was successfully updated.' }
        format.json { render :show, status: :ok, location: @onibus }
      else
        format.html { render :edit }
        format.json { render json: @onibus.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /onibuses/1
  # DELETE /onibuses/1.json
  def destroy
    @onibus.destroy
    respond_to do |format|
      format.html { redirect_to onibuses_url, notice: 'Onibus was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_onibus
      @onibus = Onibus.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def onibus_params
      params.require(:onibus).permit(:Id_Onibus, :Apelido, :Terminal_Partida, :Terminal_Chegada, :CodigoOnibus)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/localizacao_onibuses_helper.rb
module LocalizacaoOnibusesHelper
end

app/helpers/onibuses_helper.rb
module OnibusesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GrupoP</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/localizacao_onibuses/_form.html.erb
<%= form_with(model: localizacao_onibus) do |form| %>
  <% if localizacao_onibus.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(localizacao_onibus.errors.count, "error") %> prohibited this localizacao_onibus from being saved:</h2>

      <ul>
        <% localizacao_onibus.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Usuario_Id %>
    <%= form.number_field :Usuario_Id %>
  </div>

  <div class="field">
    <%= form.label :Onibus_Id_Onibus %>
    <%= form.text_field :Onibus_Id_Onibus %>
  </div>

  <div class="field">
    <%= form.label :Localizacao %>
    <%= form.text_field :Localizacao %>
  </div>

  <div class="field">
    <%= form.label :Data_2 %>
    <%= form.date_select :Data_2 %>
  </div>

  <div class="field">
    <%= form.label :Hora %>
    <%= form.datetime_select :Hora %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/localizacao_onibuses/edit.html.erb
<h1>Editing Localizacao Onibus</h1>

<%= render 'form', localizacao_onibus: @localizacao_onibus %>

<%= link_to 'Show', @localizacao_onibus %> |
<%= link_to 'Back', localizacao_onibuses_path %>

app/views/localizacao_onibuses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Localizacao Onibuses</h1>

<table>
  <thead>
    <tr>
      <th>Usuario id</th>
      <th>Onibus id onibus</th>
      <th>Localizacao</th>
      <th>Data 2</th>
      <th>Hora</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @localizacao_onibuses.each do |localizacao_onibus| %>
      <tr>
        <td><%= localizacao_onibus.Usuario_Id %></td>
        <td><%= localizacao_onibus.Onibus_Id_Onibus %></td>
        <td><%= localizacao_onibus.Localizacao %></td>
        <td><%= localizacao_onibus.Data_2 %></td>
        <td><%= localizacao_onibus.Hora %></td>
        <td><%= link_to 'Show', localizacao_onibus %></td>
        <td><%= link_to 'Edit', edit_localizacao_onibus_path(localizacao_onibus) %></td>
        <td><%= link_to 'Destroy', localizacao_onibus, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Localizacao Onibus', new_localizacao_onibus_path %>

app/views/localizacao_onibuses/new.html.erb
<h1>New Localizacao Onibus</h1>

<%= render 'form', localizacao_onibus: @localizacao_onibus %>

<%= link_to 'Back', localizacao_onibuses_path %>

app/views/localizacao_onibuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Usuario id:</strong>
  <%= @localizacao_onibus.Usuario_Id %>
</p>

<p>
  <strong>Onibus id onibus:</strong>
  <%= @localizacao_onibus.Onibus_Id_Onibus %>
</p>

<p>
  <strong>Localizacao:</strong>
  <%= @localizacao_onibus.Localizacao %>
</p>

<p>
  <strong>Data 2:</strong>
  <%= @localizacao_onibus.Data_2 %>
</p>

<p>
  <strong>Hora:</strong>
  <%= @localizacao_onibus.Hora %>
</p>

<%= link_to 'Edit', edit_localizacao_onibus_path(@localizacao_onibus) %> |
<%= link_to 'Back', localizacao_onibuses_path %>

app/views/onibuses/_form.html.erb
<%= form_with(model: onibus) do |form| %>
  <% if onibus.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(onibus.errors.count, "error") %> prohibited this onibus from being saved:</h2>

      <ul>
        <% onibus.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Id_Onibus %>
    <%= form.text_field :Id_Onibus %>
  </div>

  <div class="field">
    <%= form.label :Apelido %>
    <%= form.text_field :Apelido %>
  </div>

  <div class="field">
    <%= form.label :Terminal_Partida %>
    <%= form.text_field :Terminal_Partida %>
  </div>

  <div class="field">
    <%= form.label :Terminal_Chegada %>
    <%= form.text_field :Terminal_Chegada %>
  </div>

  <div class="field">
    <%= form.label :CodigoOnibus %>
    <%= form.number_field :CodigoOnibus %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/onibuses/edit.html.erb
<h1>Editing Onibus</h1>

<%= render 'form', onibus: @onibus %>

<%= link_to 'Show', @onibus %> |
<%= link_to 'Back', onibuses_path %>

app/views/onibuses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Onibuses</h1>

<table>
  <thead>
    <tr>
      <th>Id onibus</th>
      <th>Apelido</th>
      <th>Terminal partida</th>
      <th>Terminal chegada</th>
      <th>Codigoonibus</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @onibuses.each do |onibus| %>
      <tr>
        <td><%= onibus.Id_Onibus %></td>
        <td><%= onibus.Apelido %></td>
        <td><%= onibus.Terminal_Partida %></td>
        <td><%= onibus.Terminal_Chegada %></td>
        <td><%= onibus.CodigoOnibus %></td>
        <td><%= link_to 'Show', onibus %></td>
        <td><%= link_to 'Edit', edit_onibus_path(onibus) %></td>
        <td><%= link_to 'Destroy', onibus, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Onibus', new_onibus_path %>

app/views/onibuses/new.html.erb
<h1>New Onibus</h1>

<%= render 'form', onibus: @onibus %>

<%= link_to 'Back', onibuses_path %>

app/views/onibuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id onibus:</strong>
  <%= @onibus.Id_Onibus %>
</p>

<p>
  <strong>Apelido:</strong>
  <%= @onibus.Apelido %>
</p>

<p>
  <strong>Terminal partida:</strong>
  <%= @onibus.Terminal_Partida %>
</p>

<p>
  <strong>Terminal chegada:</strong>
  <%= @onibus.Terminal_Chegada %>
</p>

<p>
  <strong>Codigoonibus:</strong>
  <%= @onibus.CodigoOnibus %>
</p>

<%= link_to 'Edit', edit_onibus_path(@onibus) %> |
<%= link_to 'Back', onibuses_path %>